const { EventEmitter } = require("events");
const { db } = require("./db");
const ollama = require("../../services/ollamaService");
const { validateClaims } = require("../../services/claimValidator");
const { retrieve } = require("../../services/knowledgeService");
const { chooseMedia } = require("../../services/mediaSelectionService");
const productData = require("../../services/productDataService");

const events = new EventEmitter();
const trusted = new Set(["own_content","approved","shared_by_glantier"]);
let timer;
function emitEvent(type,message,severity="info",taskId=null){ const result=db.prepare("INSERT INTO agent_events(event_type,message,severity,related_task_id) VALUES(?,?,?,?)").run(type,message,severity,taskId); const event={id:result.lastInsertRowid,event_type:type,message,severity,related_task_id:taskId,created_at:new Date().toISOString()}; events.emit("event",event); return event; }
function state(key,value){db.prepare("INSERT INTO agent_state(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").run(key,String(value));}
function queueTask({taskType,title,description="",priority="normal",contentId=null,postId=null,userAction=false}){const result=db.prepare("INSERT INTO agent_tasks(task_type,title,description,priority,related_content_id,related_post_id,requires_user_action) VALUES(?,?,?,?,?,?,?)").run(taskType,title,description,priority,contentId,postId,userAction?1:0);emitEvent("task_queued",title,"info",result.lastInsertRowid);return result.lastInsertRowid;}
function isCampaignValid(content){return !content.end_date || new Date(`${content.end_date}T23:59:59`)>=new Date();}
function connected(platforms){return platforms.every(platform=>db.prepare("SELECT 1 FROM social_accounts WHERE platform=? AND status='connected'").get(platform));}
function nextAvailableSlot(mode="week"){const start=new Date();start.setMinutes(0,0,0);if(mode==="today")start.setHours(Math.max(start.getHours()+1,9));else{start.setDate(start.getDate()+1);start.setHours(10);}for(let day=0;day<8;day+=1){const candidate=new Date(start);candidate.setDate(start.getDate()+day);if(mode==="today"&&day>0)break;const date=candidate.toISOString().slice(0,10);if(!db.prepare("SELECT 1 FROM studio_posts WHERE status='scheduled' AND date(scheduled_at)=? LIMIT 1").get(date))return candidate.toISOString();}return null;}
async function processTask(task){
  db.prepare("UPDATE agent_tasks SET status='working',started_at=CURRENT_TIMESTAMP WHERE id=? AND status='queued'").run(task.id); state("current_task",task.title); emitEvent("task_started",`Ik ben begonnen met: ${task.title.toLowerCase()}.`,"info",task.id);
  try{
    if(task.task_type!=="analyze_content") throw new Error("Dit taaktype wordt nog niet automatisch uitgevoerd.");
    const content=db.prepare(`SELECT c.*,cp.name campaign_name,cp.end_date,m.media_type,m.original_name FROM content_items c LEFT JOIN campaigns cp ON cp.id=c.campaign_id LEFT JOIN media_assets m ON m.content_item_id=c.id WHERE c.id=?`).get(task.related_content_id);
    if(!content)throw new Error("Contentitem bestaat niet meer.");
    if(!trusted.has(content.usage_permission)){db.prepare("UPDATE agent_tasks SET status='waiting',requires_user_action=1 WHERE id=?").run(task.id);emitEvent("rights_blocked",`Ik kan ${content.title} nog niet voorbereiden omdat de gebruiksrechten op onbekend staan.`,"warning",task.id);return;}
    const cooldown=Number(db.prepare("SELECT value FROM settings WHERE key='contentReuseCooldownDays'").get()?.value||21);
    const duplicate=!task.related_post_id&&db.prepare("SELECT 1 FROM studio_posts WHERE content_item_id=? AND created_at>=datetime('now',?) LIMIT 1").get(content.id,`-${cooldown} days`);
    if(duplicate){db.prepare("UPDATE agent_tasks SET status='waiting',requires_user_action=1,error_message='Content cooldown actief' WHERE id=?").run(task.id);emitEvent("duplicate_blocked",`Ik gebruik ${content.title} niet opnieuw omdat de cooldown nog actief is.`,"warning",task.id);return;}
    const sources=retrieve([content.product_reference,content.campaign_name,content.category,content.title].filter(Boolean).join(" "),{campaignId:content.campaign_id});
    const product=productData.factualContext(productData.find(content.product_reference));
    const grounded={...content,notes:[product?`PRIMAIRE ORIVÈA PRODUCTDATA: ${JSON.stringify(product)}`:"",content.notes,sources.map(source=>`BRON ${source.document_title}: ${source.content}`).join("\n")].filter(Boolean).join("\n\n")};
    const generated=await ollama.generateSocialCopy(grounded,task.description||""); const claims=validateClaims(generated.output,{});
    db.prepare("INSERT INTO ai_generations(content_item_id,model,confidence,status,latency_ms,error_message) VALUES(?,?,?,?,?,?)").run(content.id,generated.model,generated.output.confidence,generated.fallback?"fallback":"success",generated.latencyMs,generated.error||null);
    if(!claims.valid){db.prepare("UPDATE agent_tasks SET status='waiting',requires_user_action=1,error_message=? WHERE id=?").run("Niet-gevalideerde claim",task.id);emitEvent("claim_blocked",`Ik heb de tekst voor ${content.title} geblokkeerd omdat die een niet-gevalideerde claim bevat.`,"warning",task.id);return;}
    const platforms=generated.output.recommended_channels; const created=db.transaction(()=>{const postId=task.related_post_id||db.prepare("INSERT INTO studio_posts(content_item_id,title,cta,target_url,status) VALUES(?,?,?,?, 'draft')").run(content.id,content.title,generated.output.cta,generated.output.target_url).lastInsertRowid;if(task.related_post_id)db.prepare("DELETE FROM post_platforms WHERE post_id=?").run(postId);for(const platform of platforms)db.prepare("INSERT INTO post_platforms(post_id,platform,caption,hashtags,status) VALUES(?,?,?,?, 'draft')").run(postId,platform,generated.output[`caption_${platform}`],generated.output[`hashtags_${platform}`].join(" "));return postId;})();
    const selectedMedia=content.media_type?db.prepare("SELECT * FROM media_assets WHERE content_item_id=? AND disabled=0 LIMIT 1").get(content.id):chooseMedia(content,platforms[0]);
    const duplicateCaption=platforms.some(platform=>db.prepare("SELECT 1 FROM post_platforms WHERE caption=? AND post_id<>? LIMIT 1").get(generated.output[`caption_${platform}`],created));
    const quality=Math.max(0,100-(duplicateCaption?20:0)-(content.product_reference&&!product?20:0)-(!selectedMedia?15:0)-(!sources.length?10:0)-(!isCampaignValid(content)?50:0));const qualityStatus=quality>=90?"ready":quality>=75?"review_recommended":"draft";
    db.transaction(()=>{db.prepare("UPDATE studio_posts SET quality_score=?,quality_status=?,knowledge_sources_used=?,content_brief=? WHERE id=?").run(quality,qualityStatus,JSON.stringify(sources.map(source=>({document_id:source.document_id,title:source.document_title,chunk_id:source.id}))),JSON.stringify({objective:"relevante ORIVÈA content",audience:"ORIVÈA volgers",product:content.product_reference||null,campaign:content.campaign_name||null,platforms,media_reason:selectedMedia?"Beste geldige mediamatch":"Geen geschikte media",message_angle:content.category,cta:generated.output.cta}),created);if(selectedMedia)db.prepare("INSERT OR IGNORE INTO post_media(post_id,media_asset_id,position) VALUES(?,?,0)").run(created,selectedMedia.id);for(const source of sources){db.prepare("INSERT OR IGNORE INTO post_knowledge_sources(post_id,document_id,chunk_id,reason) VALUES(?,?,?,?)").run(created,source.document_id,source.id,"RAG context");db.prepare("INSERT INTO content_knowledge_links(content_item_id,document_id,relevance) VALUES(?,?,?) ON CONFLICT(content_item_id,document_id) DO UPDATE SET relevance=MAX(relevance,excluded.relevance)").run(content.id,source.document_id,source.score);}})();
    const autoApprove=(db.prepare("SELECT value FROM settings WHERE key='autoApproveTrustedContent'").get()?.value||"false")==="true"; const threshold=Number(db.prepare("SELECT value FROM settings WHERE key='aiAutoApproveMinConfidence'").get()?.value||0.9);
    const requestedMode=task.description==="schedule:today"?"today":task.description==="schedule:week"?"week":null;
    const maySchedule=(requestedMode||autoApprove)&&quality>=90&&!duplicateCaption&&!generated.fallback&&generated.output.confidence>=threshold&&isCampaignValid(content)&&/^https:\/\/(www\.)?orivea\.nl/i.test(generated.output.target_url)&&connected(platforms);
    if(maySchedule){const scheduled=nextAvailableSlot(requestedMode||"week");if(!scheduled)throw new Error("Er is geen vrij publicatiemoment binnen de gekozen periode.");db.prepare("UPDATE studio_posts SET status='scheduled',approved_at=CURRENT_TIMESTAMP,approved_by='ORIVÈA Content Agent',scheduled_at=? WHERE id=?").run(scheduled,created);db.prepare("UPDATE post_platforms SET status='scheduled' WHERE post_id=?").run(created);emitEvent("post_scheduled",`Ik heb ${content.title} voorbereid en ingepland.`,"success",task.id);}else{emitEvent("draft_created",`Ik heb voor ${content.title} aparte social captions voorbereid. Ze wachten op jouw goedkeuring.`,"success",task.id);}
    db.prepare("UPDATE agent_tasks SET status='done',related_post_id=?,completed_at=CURRENT_TIMESTAMP WHERE id=?").run(created,task.id);state("last_ollama_contact",new Date().toISOString());
  }catch(error){db.prepare("UPDATE agent_tasks SET status='failed',completed_at=CURRENT_TIMESTAMP,error_message=? WHERE id=?").run(error.message,task.id);emitEvent("task_failed",`Ik kon ${task.title.toLowerCase()} niet afronden: ${error.message}`,"error",task.id);}finally{state("current_task","");state("last_activity",new Date().toISOString());}
}
async function tick(){state("last_heartbeat",new Date().toISOString());if((db.prepare("SELECT value FROM settings WHERE key='agentPaused'").get()?.value||"false")==="true")return;const task=db.prepare("SELECT * FROM agent_tasks WHERE status='queued' ORDER BY CASE priority WHEN 'high' THEN 1 WHEN 'normal' THEN 2 ELSE 3 END,created_at LIMIT 1").get();if(task)await processTask(task);}
function dailyStart(){const today=new Date().toISOString().slice(0,10);if(getStateValue("last_daystart_date")===today)return;const planned=db.prepare("SELECT COUNT(*) count FROM studio_posts WHERE date(scheduled_at)=date('now','localtime') AND status='scheduled'").get().count;const platforms=["instagram","facebook","tiktok","pinterest"];const missing=platforms.filter(platform=>!db.prepare("SELECT 1 FROM social_accounts WHERE platform=? AND status='connected'").get(platform));for(const platform of missing){const exists=db.prepare("SELECT 1 FROM agent_tasks WHERE task_type='connect_platform' AND title=? AND status IN ('queued','waiting')").get(`${platform} koppelen`);if(!exists){const id=queueTask({taskType:"connect_platform",title:`${platform} koppelen`,description:`${platform} wacht op een officiële OAuth-koppeling.`,priority:"high",userAction:true});db.prepare("UPDATE agent_tasks SET status='waiting' WHERE id=?").run(id);}}const actions=db.prepare("SELECT COUNT(*) count FROM agent_tasks WHERE requires_user_action=1 AND status IN ('waiting','failed')").get().count;emitEvent("daily_start",`Goedemorgen. Vandaag staan ${planned} posts gepland. Er zijn ${actions} acties voor jou en ${missing.length} social accounts zijn nog niet gekoppeld.`,actions||missing.length?"warning":"success");state("last_daystart_date",today);}
function getStateValue(key){return db.prepare("SELECT value FROM agent_state WHERE key=?").get(key)?.value||"";}
function startAgent(){if(timer)return;dailyStart();tick();timer=setInterval(()=>{dailyStart();tick();},15000);timer.unref?.();}
module.exports={events,emitEvent,state,queueTask,tick,startAgent,dailyStart};
